services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: appdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/sql:/docker-entrypoint-initdb.d      

  cube:
    image: cubejs/cube:v1.3.37
    ports:
      - '4000:4000'
      - '15432:15432'
    environment:
      CUBEJS_DEV_MODE: true    
      CUBEJS_DB_HOST: postgres
      CUBEJS_DB_NAME: appdb
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: mysecretpassword
      CUBEJS_DB_TYPE: postgres
      CUBEJS_API_SECRET: secret
      CUBEJS_SCHEMA_PATH: model
    volumes:
      - ./src/cube:/cube/conf

volumes:
  postgres-data:
